### ISSUE TITLE
你好，请问实际开发过程中，API验证方式 有没有好点的建议或者 文章让我们借鉴呢？非常感谢！期待您的回复，谢谢！

### ISSUE THREAD

**Issue by xingwen93** [qiniudemo/qiniu-live-server#3]
你好，请问实际开发过程中，API验证方式 有没有好点的建议或者 文章让我们借鉴呢？
非常感谢！期待您的回复，谢谢！

**Comment by jemygraw** [comment]
http://xingrz.me/2013/2013-06-16/restful-api-authorization.html
